language: go

stages:
  - fmt
  - test
  - codecov
  - build

go:
  - 1.15.x

env: GO111MODULE=on

before_install:
  - go get -u github.com/kyoh86/richgo
  - go get -u github.com/mitchellh/gox
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

matrix:
  include:
    - stage: fmt
      go: 1.15.x
      script: make fmt
    - stage: test
      go: 1.15.x
      script: make test
    - stage: codecov
      go: 1.15.x
      script: make codecov
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: build
      go: 1.15.x
      script: make build
